[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
de_garden = "H3B2URUN8BMxZvxx6yit2n8sRRWGo8bBdew4yDosurjG"

[programs.localnet]
de_garden = "H3B2URUN8BMxZvxx6yit2n8sRRWGo8bBdew4yDosurjG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
script = "npx ts-node scripts/script.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
